spring.application.name=migration_project
# Database URL (replace migration_db with your actual DB name)
# Instead of hardcoding, tell Spring to read from the environment
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate properties
#spring.jpa.hibernate.ddl-auto=create-drop
#this will delete whole table once you execute it
spring.jpa.hibernate.ddl-auto=update
#this will create table in postgressql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.springdoc=DEBUG
springdoc.override-with-generic-response=false
